# Generated by Django 5.1.3 on 2024-11-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_cardapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardApplication',
        ),
    ]
